### PR TITLE
Implementation of the verified github account in the edit profile page

### PR DESCRIPTION
**Pull request by joaoaguiam**
After talking with @oznekenzo and @oed, I implemented the verification process of the github account by allowing the user to submit a link to a file under their gist account with the user account address.

A demo and walkthrough of the code is available here: [https://youtu.be/SgZDBlVQZxc](https://youtu.be/SgZDBlVQZxc )

This implementation is linked to the issue #157

### CODE REVIEW

**Comment by oed** [comment]
Thanks @joaoaguiam this is super cool! Seems pretty solid. I just have a few questions:
Why do you have to put the full link to your github account? Wouldn't just the username be enough?

I think it might be useful to make the `src/utils/accountVerifiers.js` into a separate library. That would allow devs that use the 3box-js library to independently very the github accounts if they need/want. This would also allow us to generalize this stuff. I'm going to try to do a more technical writeup of that today, see here: https://github.com/uport-project/3box-dapp/issues/141#issuecomment-441155056

**Comment by michaelsena** [comment]
@joaoaguiam it would also be helpful to know if we can autogenerate a Gist file, including the user's DID. I think that's the main thing I'm trying to understand - is how can we make it as easy/automatic as possible for the user to generate a Gist? Ideally it would be as easy as clicking verify my account, and it creates the file for me.

**Comment by joaoaguiam** [comment]
@michaelsena That's a good point. We may simplify the user by calling the POST gist API https://developer.github.com/v3/gists/#create-a-gist with the content already pre-built and from this call obtain the githubProof link.

**Comment by oed** [comment]
Seems like that flow requires us to do an OAuth with github though. Which seems a bit bloated for what we are trying to do.

**Comment by oznekenzo** [comment]
@oed does this require anything from me at the moment?

**Comment by oed** [comment]
@oznekenzo Nope, we will likely close this since we are implementing the verifications in the 3box-js lib. Then we'll have a separate story for integrating that in the dapp.

**Comment by oed** [comment]
Thanks for you're hard work on this @joaoaguiam! Your code that's in the library now will be available in the dapp soon!

**Comment by joaoaguiam** [comment]
Welcome @oed If you need any help on something else just let me know ;)

**Pull request closed without merging**
