### PR TITLE
Remove careers page, link to Lever

### PR DESCRIPTION
**Pull request by PaulLeCam**
Works as expected locally

### CODE REVIEW

**Review by oed — COMMENTED** [review]
Looks good, but does @zachferland need to fix something for the deployment again?

**Comment by PaulLeCam** [comment]
I don't know, I think Zach added a fix in master so hopefully it's good now, but I don't know if there's a way to check the deployment before it's merged to develop?

**Comment by oed** [comment]
Let's wait until zach can have a look. I think it might have been something that is needed each time.

**Comment by oed** [comment]
this PR is to `master` btw.

**Comment by PaulLeCam** [comment]
Ah good catch, sorry I didn't notice, I thought develop was set as the base by default

**Review by oed — APPROVED** [review]
great

**Pull request merged**
