### PR TITLE
Remove chatbox component

### PR DESCRIPTION
**Pull request by PaulLeCam**

### CODE REVIEW

**Review by oed — COMMENTED** [review]
Looks good. Let's make sure it builds properly then we should just be able to merge with master and have it auto published.

**Comment by PaulLeCam** [comment]
Any way to check the build please?
I tried running the `build` script but I get `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

**Comment by oed** [comment]
Not completely sure. Can you  check in with @zachferland when he's online?

**Comment by zachferland** [comment]
may need to NODE_OPTIONS=--max-old-space-size=4096, unclear exacltly why but this build has taken up a huge amount of memory to build

**Review by zachferland — APPROVED** [review]

**Comment by PaulLeCam** [comment]
Thanks! It works with the added flag, should be good to merge 👍

**Comment by x5engine** [comment]
That's a workaround and it works sometimes but guys you need to find what's sucking so much memory to make it build this much slower and bigger.

**Pull request merged**
